version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file index-photos.yaml --s3-bucket codepipeline-us-east-1-529141990229 --output-template-file outputsamtemplate.yml
artifacts:
  type: zip
  files:
    - index-photos.yaml
    - outputsamtemplate.yml
