AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: CD Demo Lambda
Resources:
  indexphotos:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: index-photos-2
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: ./index-photos-copy
      Description: "Upload function for CD Demo"
      MemorySize: 128
      Timeout: 30
      Role: "arn:aws:iam::064696336202:role/service-role/index-photos-role"
      Environment:
        Variables:
          REGION: us-east-1
  searchphotos:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: search-photos-2
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: ./search-photos-copy
      Description: "Search function for CD Demo"
      MemorySize: 128
      Timeout: 30
      Role: "arn:aws:iam::064696336202:role/service-role/search-photos-role-jw3smc8x"
      Environment:
        Variables:
          REGION: us-east-1
